// Shared content data for jcapshaw.com prototype
window.SITE_DATA = {
  posts: [
    {
      slug: "real-cost-bad-product-data",
      title: "The Real Cost of Bad Product Data in Distribution",
      dek: "Most distributors know their product data is a mess. Few understand how much it's silently costing them — in wasted labor, lost orders, and platform rollouts that were rotten before they shipped.",
      date: "2026-04-18",
      read: "12 min",
      topic: "Commerce Architecture",
      featured: true,
      excerpt: "Most distributors know their product data is a mess. Few understand how much it's silently costing them.",
    },
    {
      slug: "erp-not-the-platform",
      title: "The ERP Is Not the Platform",
      date: "2026-04-04",
      read: "9 min",
      topic: "Enterprise Systems",
      excerpt: "Why ERP-as-system-of-record is a decades-old assumption that quietly breaks every modern commerce initiative.",
    },
    {
      slug: "b2b-commerce-isnt-b2c-with-login",
      title: "Why B2B Commerce Isn't B2C With a Login Page",
      date: "2026-03-21",
      read: "11 min",
      topic: "Commerce Architecture",
      excerpt: "The biggest architectural mistake in B2B digital commerce is treating it like a B2C storefront with authentication bolted on. The domains are fundamentally different.",
    },
    {
      slug: "search-is-the-product",
      title: "Search Is the Product",
      date: "2026-03-07",
      read: "8 min",
      topic: "Commerce Architecture",
      excerpt: "In B2B distribution, search isn't a feature. It's the product. Here's how to reason about relevance, intent, and catalog quality.",
    },
    {
      slug: "ai-cant-save-bad-procurement",
      title: "AI Can't Save You From Bad Procurement",
      date: "2026-02-24",
      read: "10 min",
      topic: "Applied AI",
      excerpt: "The gap between the promise and the reality of AI in procurement is enormous, and it's still growing. Here's what's real, what isn't, and why our disappointment will mostly be our own fault.",
    },
    {
      slug: "inventory-is-a-story",
      title: "Inventory Is a Story Your ERP Tells About Itself",
      date: "2026-02-10",
      read: "7 min",
      topic: "Distribution & Industrial",
      excerpt: "Inventory data is not a snapshot of reality. It's an opinionated narrative. Treat it accordingly.",
    },
    {
      slug: "pricing-engines-honest",
      title: "What an Honest Pricing Engine Looks Like",
      date: "2026-01-28",
      read: "13 min",
      topic: "Commerce Architecture",
      excerpt: "Contract pricing in distribution is not a rules problem. It's a trust problem. Rules are how we pretend otherwise.",
    },
    {
      slug: "notes-on-solo-consulting",
      title: "Notes On Running a Solo Practice",
      date: "2026-01-14",
      read: "6 min",
      topic: "Short Notes",
      excerpt: "Eighteen months of running a one-person consultancy serving distribution clients. What worked, what I'd change.",
    },
    {
      slug: "edi-isnt-dead",
      title: "EDI Isn't Dead. It's Load-Bearing.",
      date: "2025-12-18",
      read: "9 min",
      topic: "Enterprise Systems",
      excerpt: "Every few years someone announces EDI's demise. Every few years it remains the backbone of trillions in B2B commerce. Why it persists — and why that's okay.",
    },
    {
      slug: "architecture-for-ambiguity",
      title: "Architecture for Ambiguity",
      date: "2025-12-02",
      read: "11 min",
      topic: "Systems Design",
      excerpt: "How to design systems when the business can't tell you what it wants yet.",
    },
    {
      slug: "catalog-is-contract",
      title: "Your Catalog Is a Contract",
      date: "2025-11-15",
      read: "8 min",
      topic: "Commerce Architecture",
      excerpt: "Every SKU you publish is a promise. Most distributors make promises they can't keep.",
    },
    {
      slug: "agents-vs-workflows",
      title: "Agents vs. Workflows: A Practical Distinction",
      date: "2025-10-28",
      read: "10 min",
      topic: "Applied AI",
      excerpt: "The word 'agent' is doing a lot of work lately. Here's a frame for deciding when you actually need one.",
    },
  ],

  topics: [
    { name: "Commerce Architecture", desc: "Platforms, catalogs, data models, and system seams in B2B.", count: 11 },
    { name: "Distribution & Industrial", desc: "How physical-goods businesses actually work — and how software can stop fighting them.", count: 7 },
    { name: "Applied AI", desc: "AI in procurement, search, and product data — without the hand-waving.", count: 5 },
    { name: "Enterprise Systems", desc: "ERPs, integrations, middleware, and other load-bearing scar tissue.", count: 8 },
  ],

  projects: [
    {
      name: "Ledgerline",
      desc: "Contract pricing & quote engine for mid-market electrical distributors. Multi-tenant, backed by a normalized catalog and audit-grade pricing traces.",
      stack: "Postgres · Elixir · Typescript",
      status: "live",
      years: "2024 — now",
    },
    {
      name: "Catalog Fabric",
      desc: "Product data normalization pipeline: ingests UNSPSC-tagged supplier feeds, reconciles attribute schemas, outputs a single canonical catalog.",
      stack: "Python · DuckDB · dbt",
      status: "live",
      years: "2023 — now",
    },
    {
      name: "Field Order Desk",
      desc: "Lightweight order entry UX for outside sales reps. Offline-first, tuned for trade counter workflows rather than SaaS conventions.",
      stack: "React Native · SQLite",
      status: "wip",
      years: "2025 — now",
    },
    {
      name: "RFQ Triage",
      desc: "LLM-assisted triage for inbound RFQs: classifies intent, extracts line items from messy attachments, routes to the right desk.",
      stack: "Python · OpenAI · Postgres",
      status: "wip",
      years: "2025 — now",
    },
    {
      name: "Tariff Desk",
      desc: "Historical tariff & landed-cost calculator for imported electrical goods. Archived — the dataset is now part of Ledgerline.",
      stack: "Go · SQLite",
      status: "archive",
      years: "2022 — 2024",
    },
  ],

  talks: [
    { slug: "naed-quiet-shape", date: "Oct 2025", title: "The Quiet Shape of B2B Commerce", venue: "NAED Adventure · Dallas", audience: "~420 distribution executives", duration: "40 min + Q&A", abstract: "A walk through why B2B commerce platforms keep underperforming expectations — and what a distributor-native architecture actually looks like.", slides: true, recording: true },
    { slug: "idea-product-data", date: "Aug 2025", title: "Product Data Is Everyone's Problem", venue: "IDEA eBiz Forum · Chicago", audience: "~280 IT + e-commerce leaders", duration: "35 min", abstract: "Why product data quality is the silent governor on every digital initiative in distribution, and how to assign ownership without a committee.", slides: true, recording: false },
    { slug: "dsg-erp-platform", date: "May 2025", title: "Why Your ERP Isn't a Platform", venue: "Distribution Strategy · Denver", audience: "~150 operations leaders", duration: "45 min", abstract: "The assumption that the ERP can serve as the system of record for commerce is decades old and silently breaks every modern initiative. A case for separating the book of record from the book of experience.", slides: true, recording: true },
    { slug: "b2b-online-search", date: "Feb 2025", title: "Search Is The Product", venue: "B2B Online · Chicago", audience: "~800 commerce practitioners", duration: "30 min", abstract: "In B2B distribution, search isn't a feature — it's the product. How to reason about relevance, intent, and catalog quality in that order.", slides: true, recording: true },
    { slug: "naw-ai-procurement", date: "Oct 2024", title: "AI in Industrial Procurement", venue: "NAW Executive Summit · Washington", audience: "~600 executives", duration: "40 min", abstract: "What AI in procurement actually does well today, where it falls over, and the quiet unglamorous work that makes the rest possible.", slides: true, recording: false },
  ],

  caseStudies: [
    {
      slug: "southeast-electrical-replatform",
      client: "Regional Electrical Distributor",
      clientMeta: "3rd generation · 14 branches · Southeast",
      title: "Replatforming the customer portal without a big-bang cutover",
      period: "2024 — 2025",
      role: "Architect, engagement lead",
      stack: "Commercetools · Postgres · Elixir · React",
      summary: "Phased replatforming of a 15-year-old customer portal with 2,400 active B2B accounts. No maintenance window longer than 90 seconds. Zero order loss during cutover.",
      outcomes: [
        { metric: "+34%", label: "portal session depth vs. prior quarter" },
        { metric: "−62%", label: "support tickets tagged 'cannot find product'" },
        { metric: "0", label: "orders lost during migration" },
        { metric: "7 months", label: "from kickoff to full cutover" },
      ],
      problem: "The prior portal was a bolted-on storefront with authentication stapled over an ERP query layer. Pricing rules were scattered across the ERP, a middleware layer, and the storefront itself. No single system could explain why a given customer saw a given price, which made every pricing incident a three-way investigation.",
      approach: "We treated the catalog and the pricing engine as separate concerns from the beginning, and the portal as a thin read-model over both. Every price seen in the UI carried a trace ID back to the rule that produced it, so support could answer 'why this price' in under a minute instead of three calls.",
    },
    {
      slug: "unspsc-catalog-fabric",
      client: "Industrial Supply Co-op",
      clientMeta: "42 member distributors · Southeast region",
      title: "A canonical catalog for a 42-member distribution co-op",
      period: "2023 — ongoing",
      role: "Architect, primary implementer",
      stack: "Python · DuckDB · dbt · Postgres",
      summary: "One normalized catalog feeding 42 member distributors from ~180 supplier feeds. Versioned schemas, confidence-scored records, and a reconciliation console that is actually used.",
      outcomes: [
        { metric: "180 →  1", label: "supplier feeds normalized into one canonical catalog" },
        { metric: "96.4%", label: "UNSPSC 8-digit coverage, up from 41%" },
        { metric: "3.2 days", label: "median supplier-feed ingestion to canonical publish" },
      ],
      problem: "Forty-two members, each with their own idiosyncratic attribute schemas, negotiating with the same suppliers. Every member was doing the same normalization work in parallel, badly. Nobody had a shared catalog they trusted enough to use.",
      approach: "A shared ingestion pipeline with member-scoped overrides. Every rule is versioned; every record carries its provenance and a confidence score. The reconciliation UI is deliberately simple — a stream of 'these two records look like the same thing, agree?' pairings, because that's the only part a human actually needs to do.",
    },
    {
      slug: "rfq-triage",
      client: "Electrical Contractor Supply",
      clientMeta: "Mid-market · East Coast",
      title: "Triaging 1,800 weekly RFQs without hiring a team",
      period: "2025",
      role: "Architect",
      stack: "Python · OpenAI · Postgres",
      summary: "An LLM-assisted triage layer that reads inbound RFQ emails and attachments, extracts line items with confidence scores, and routes to the right desk. No black boxes — every extraction is inspectable and reversible.",
      outcomes: [
        { metric: "18 hrs → 2 hrs", label: "median RFQ response time" },
        { metric: "84%", label: "auto-extracted line items accepted without edits" },
        { metric: "0 headcount", label: "added to the quoting desk" },
      ],
      problem: "The quoting desk was drowning in inbound RFQs — most in PDF form, many from fax-to-email pipelines, some as phone-camera photos of handwritten lists. Junior quoters were spending 70% of their time transcribing before they could even start quoting.",
      approach: "Build a triage layer, not an autonomous agent. The system proposes line-item extractions with confidence scores; humans accept, reject, or edit. Every accepted extraction becomes training signal for the next week's rules. The goal was never 'fully automated quoting' — it was 'make a quoter twice as productive.'",
    },
  ],
};
